const KEY='snowy-alpha-state-v1';
const initial={onboarded:false,name:'Herbert',focus:'',memories:[],dna:[],watches:[],messages:[],feedback:[]};
let state=load(); let view=state.onboarded?'home':'welcome';
function load(){try{return {...initial,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...initial}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function remember(text,type='episodic',confidence=.7){state.memories.unshift({id:crypto.randomUUID(),text,type,confidence,at:new Date().toISOString()});state.memories=state.memories.slice(0,80)}
function learnDNA(text,confidence=.65){if(!state.dna.some(x=>x.text.toLowerCase()===text.toLowerCase())) state.dna.unshift({id:crypto.randomUUID(),text,confidence,status:'inferred',at:new Date().toISOString()})}
function infer(text){const t=text.toLowerCase();remember(text);
 if(/prefiro|gosto de|quero que você|quero que voce/.test(t)) learnDNA(text,.78);
 if(/importante|prioridade/.test(t)) learnDNA('Valoriza que a Snowy destaque o que é realmente importante.',.72);
 if(/diret/.test(t)) learnDNA('Prefere comunicação direta quando algo merece atenção.',.86);
 if(/fique de olho|acompanhe|não me deixe esquecer|nao me deixe esquecer/.test(t)){state.watches.unshift({id:crypto.randomUUID(),text,status:'WATCHING',created:new Date().toISOString()});}
}
function response(text){const t=text.toLowerCase();
 const data=t.match(/\b\d{1,2}\/\d{1,2}\b|dia\s+\d{1,2}(?:\s+de\s+[a-zç]+)?/i);                       
 const hora=t.match(/\b\d{1,2}h(?:\d{2})?\b|\b\d{1,2}:\d{2}\b/i);if(data&&hora)return `Entendi. ${/amanhã/i.test(t)?'Amanhã, ':''}${data[0]} às ${hora[0]}. Isso é um compromisso. Vou cuidar dele com você.`;
 if(/o que.*(lembra|sabe)|meu dna|aprendeu/.test(t)){const d=state.dna.slice(0,3).map(x=>'• '+x.text).join('\n');return d?`Até agora, aprendi algumas coisas com você:\n${d}\n\nVocê pode me corrigir a qualquer momento.`:'Ainda estou começando a conhecer você. Quanto mais conversarmos, mais precisa eu fico.'}
 if(/como est[aã]o as coisas|tem algo|alguma coisa/.test(t)){if(state.watches.length)return `Está tudo tranquilo por enquanto. Estou de olho em ${state.watches.length} ${state.watches.length===1?'coisa':'coisas'} para você. Se algo realmente merecer sua atenção, vou destacar.`;return 'Está tudo tranquilo. Ainda não encontrei nada que precise da sua atenção agora.'}
 if(/fique de olho|acompanhe/.test(t)) return 'Pode deixar comigo. Coloquei isso no Snowy Watch. Nesta Alpha, vou manter esse acompanhamento registrado e trazê-lo de volta quando você consultar a Snowy.';
 if(/não guarde|nao guarde/.test(t)) return 'Entendi. Nesta Alpha, você pode apagar as memórias em Meu DNA. Na versão seguinte, essa instrução será aplicada diretamente à memória citada.';
 const direct=state.dna.find(x=>/direta/.test(x.text.toLowerCase()));
 return `${direct?'Vou ser direta: ':''}entendi. Vou manter isso no contexto da nossa relação e, se perceber que é uma preferência ou prioridade recorrente, vou confirmar com você antes de tratá-la como parte do seu DNA.`;
}
function nav(){return `<div class="nav"><div class="nav-inner">${[['home','❄️','Snowy'],['chat','💬','Conversar'],['dna','🧬','Meu DNA'],['life','◎','Minha Vida']].map(([v,i,l])=>`<button data-view="${v}" class="${view===v?'active':''}">${i}<br>${l}</button>`).join('')}</div></div>`}
function saudacao(){const h=new Date().getHours();return h>=5&&h<12?'Bom dia':h>=12&&h<18?'Boa tarde':'Boa noite'}
function render(){const app=document.querySelector('#app');
 if(view==='welcome'){app.innerHTML=`<section class="shell center"><div class="snow"><img src="apple-touch-icon.png" alt="Snowy"></div><div class="brand">SNOWY</div><h1 class="tag">Sua segunda pele.</h1><p class="sub">Uma camada inteligente entre você e você mesmo.</p><button class="primary" id="meet">Conhecer minha Snowy</button><p class="tiny">Alpha 0.1 · User 0001</p></section>`;document.querySelector('#meet').onclick=()=>{view='intro';render()};return}
 if(view==='intro'){app.innerHTML=`<section class="shell center"><div class="snow"><img src="apple-touch-icon.png" alt="Snowy"></div><h1>Olá, Herbert.<br>Eu sou a sua Snowy.</h1><p class="sub">Neste momento ainda conheço muito pouco sobre você. Mas isso vai mudar. Não preciso que você me conte sua vida inteira. Vou aprender com você.</p><p><strong>Quanto mais você vive comigo, mais sua eu me torno.</strong></p><button class="primary" id="start">Vamos começar</button></section>`;document.querySelector('#start').onclick=()=>{view='question';render()};return}
 if(view==='question'){app.innerHTML=`<section class="shell center onboard"><div class="eyebrow">NOSSO PRIMEIRO PASSO</div><h1>Qual é a primeira coisa que você gostaria que eu ajudasse a melhorar na sua vida?</h1><p class="sub">Pode me contar do seu jeito.</p><textarea id="focus" placeholder="Escreva naturalmente..."></textarea><button class="primary" id="continue">Continuar</button></section>`;document.querySelector('#continue').onclick=()=>{const x=document.querySelector('#focus').value.trim();if(!x)return;state.focus=x;remember(x,'goal',.95);learnDNA('Prioridade inicial: '+x,.9);save();view='confirm';render()};return}
 if(view==='confirm'){app.innerHTML=`<section class="shell center"><div class="snow">🧬</div><h1>Seu Snowy DNA começou.</h1><p class="sub">Entendi que, neste começo, você quer minha atenção especialmente para:</p><div class="card"><strong>${esc(state.focus)}</strong></div><p class="sub">Vou aprender com você — suas preferências, prioridades, objetivos, hábitos e limites. Você sempre poderá me corrigir.</p><h2>Você é único.<br>Assim como a sua Snowy.</h2><button class="primary" id="finish">Entrar na minha Snowy</button></section>`;document.querySelector('#finish').onclick=()=>{state.onboarded=true;state.messages=[{role:'snowy',text:'Estou começando a conhecer você. Pode falar comigo normalmente. Se quiser que eu acompanhe alguma coisa, é só me pedir.”'}];save();view='home';render()};return}
 const body=view==='home'?home():view==='chat'?chat():view==='dna'?dna():life();app.innerHTML=`<section class="shell">${body}</section>${nav()}`;bind();}
function home(){return `<div class="home-simple"><h1 class="home-title">${saudacao()}, Herbert.</h1><p class="home-calm">Está tudo tranquilo por aqui.</p><button class="primary" data-view="chat">🎙️ Falar com a Snowy</button><p class="muted" style="text-align:center;margin-top:18px">ou escreva para mim...</p></div>`}
function chat(){return `<h1 class="home-title">Conversar</h1><div class="chat" id="messages">${state.messages.map(m=>`<div class="bubble ${m.role==='user'?'user':'snowy'}">${esc(m.text)}</div>`).join('')}</div><div class="composer"><textarea id="msg" rows="3" autocomplete="off" placeholder="Fale comigo..."></textarea><<button type="button" id="mic" class="mic" aria-label="Falar com a Snowy">🎙️</button><button class="send" id="send">↑</button></div>`}
function dna(){return `<h1 class="home-title">🧬 Meu DNA</h1><p class="muted">O que estou aprendendo com você. Inferências têm confiança e podem ser corrigidas.</p><div class="list">${state.dna.length?state.dna.map(x=>`<div class="item"><strong>${esc(x.text)}</strong><br><span class="pill">${Math.round(x.confidence*100)}% confiança</span><span class="pill">${x.status}</span></div>`).join(''):'<div class="item">Ainda estamos começando.</div>'}</div><div class="card"><div class="eyebrow">MEMÓRIA</div><p>${state.memories.length} registros locais nesta Alpha.</p><button class="secondary" id="clearMemory">Apagar dados locais da Alpha</button></div>`}
function life(){return `<h1 class="home-title">◎ Minha Vida</h1><p class="muted">Primeira representação do seu Life Map.</p><div class="card"><div class="eyebrow">PRIORIDADE INICIAL</div><p><strong>${esc(state.focus||'Ainda não definida')}</strong></p></div><div class="card"><div class="eyebrow">SNOWY WATCH</div>${state.watches.length?state.watches.map(x=>`<div class="item">👁️ ${esc(x.text)}<br><span class="pill">${x.status}</span></div>`).join(''):'<p class="muted">Nada em acompanhamento.</p>'}</div>`}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});const send=document.querySelector('#send');if(send){const go=()=>{const i=document.querySelector('#msg');const text=i.value.trim();if(!text)return;state.messages.push({role:'user',text});infer(text);state.messages.push({role:'snowy',text:response(text)});save();render();setTimeout(()=>document.querySelector('#messages')?.lastElementChild?.scrollIntoView({behavior:'smooth'}),0)};send.onclick=go;document.querySelector('#msg').onkeydown=e=>{if(e.key==='Enter')go()}}
 const msg=document.querySelector('#msg');if(msg){const grow=()=>{msg.style.height='auto';msg.style.height=Math.min(msg.scrollHeight,180)+'px'};msg.addEventListener('input',grow);grow()}
 const mic=document.querySelector('#mic');if(mic)mic.onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('O reconhecimento de voz ainda não está disponível neste navegador.');return}const r=new SR();r.lang='pt-BR';r.interimResults=true;r.continuous=true;let finalText='';mic.textContent='🔴';r.onresult=e=>{let temp='';for(let n=e.resultIndex;n<e.results.length;n++){const t=e.results[n][0].transcript;if(e.results[n].isFinal)finalText+=t+' ';else temp+=t}const i=document.querySelector('#msg');if(i){i.value=(finalText+temp).trim();i.dispatchEvent(new Event('input'))}};r.onend=()=>{mic.textContent='🎙️'};r.onerror=()=>{mic.textContent='🎙️'};r.start()}
 const cm=document.querySelector('#clearMemory');if(cm)cm.onclick=()=>{if(confirm('Apagar todos os dados locais desta Alpha?')){localStorage.removeItem(KEY);state={...initial};view='welcome';render()}};
 const mo=document.querySelector('#moment');if(mo)mo.onclick=()=>{state.feedback.unshift({type:'snowy_moment',at:new Date().toISOString()});save();alert('Snowy Moment registrado. ⭐')}}
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
